apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.plugin.innkeeper.name" . }}
  labels:
    {{- include "acapy.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.acapy.secret.pluginInnkeeper.generated }}
  tenantid: {{ include "getOrGenerateUUID" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.plugin.innkeeper.name" .) "Key" "tenantid") }}
  walletkey: {{ include "getOrGenerateUUID" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.plugin.innkeeper.name" .) "Key" "walletkey") }}
  {{ else }}
  tenantid: {{ include "common.secrets.lookup" (dict "secret" (include "acapy.plugin.innkeeper.name" .) "key" "tenantid" "defaultValue" .Values.acapy.secret.pluginInnkeeper.tenantid "context" $) }}
  walletkey: {{ include "common.secrets.lookup" (dict "secret" (include "acapy.plugin.innkeeper.name" .) "key" "walletkey" "defaultValue" .Values.acapy.secret.pluginInnkeeper.walletkey "context" $) }}
  {{- end }}
