apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.api.secret.name" . }}
  labels:
    {{- include "acapy.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.acapy.secret.adminurl.generated }}
  adminurl: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.api.secret.name" .) "Key" "adminurl" "Length" 32) }}
  {{- else -}}
  adminurl: {{ Values.acapy.secret.adminurl.value }}
  {{- end }}
  jwt: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.api.secret.name" .) "Key" "jwt" "Length" 32) }}
  webhookapi: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.api.secret.name" .) "Key" "webhookapi" "Length" 32) }}
