global:
  fullnameOverride: "test-tenant-ui"
  ingressSuffix: -test.apps.silver.devops.gov.bc.ca
tenant_ui:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-ui:sha-5fdc664"
    version: 'sha-5fdc664'
    buildtime: '2022-08-04T22:16:25.869Z'
    pullPolicy: Always
  traction_api:
    endpoint: https://traction-api-test.apps.silver.devops.gov.bc.ca
  acapy_admin_api:
    endpoint: https://traction-acapy-admin-test.apps.silver.devops.gov.bc.ca/

