global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
tenant_ui:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-ui:0.2.14"
    version: "0.2.14"
    buildtime: "2022-08-04T22:16:25.869Z"
    pullPolicy: Always
  traction_api:
    endpoint: https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca
  tenant_proxy:
    endpoint: https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca
  oidc:
    active: true
    showInnkeeperAdminLogin: true
    authority: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm
    jwksUri: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm/protocol/openid-connect/certs
  ariesDetails:
    ledgerDescription: "bcovrin-test"
  smtp:
    server: apps.smtp.gov.bc.ca
    port: 25
    senderAddress: DoNotReplyTractionDEV@gov.bc.ca
    innkeeperInbox: "lucas.o'neil@gov.bc.ca,emiliano.sune@quartech.com"
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
