global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:sha-f678ca9"
    version: 'sha-f678ca9'
    buildtime: '2023-03-01T03:07:45.860Z'
    pullPolicy: Always
  secret:
    adminurl:
      generated: false
    pluginInnkeeper:
      generated: false
  plugins:
    basicmessageStorage: true
    connectionUpdate: true
    multitenantProvider: true
    tractionInnkeeper: true
  pluginValues:
    tractionInnkeeper:
      printKey: true
      printToken: true
      reservationExpiryMinutes: 2880
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
  tails:
    enabled: true
  staticArgs:
    walletName: default

postgresql:
  primary:
    resources:
      limits:
        cpu: 200m
        memory: 820Mi
      requests:
        cpu: 120m
        memory: 400Mi

tenant_proxy:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-proxy:sha-f678ca9"
    version: 'sha-f678ca9'
    buildtime: "2023-03-01T03:07:43.994Z"
    pullPolicy: Always
