acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:sha-25c438d"
    version: 'sha-25c438d'
    buildtime: '2022-10-28T01:30:31.105Z'
tenant_proxy:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-proxy:sha-2aa3709"
    version: 'sha-2aa3709'
    buildtime: "2022-01-28T18:19:10.574Z"