global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:0.2.11"
    version: '0.2.11'
    buildtime: '2022-10-28T01:30:31.105Z'
    pullPolicy: Always
  secret:
    adminurl:
      generated: false
    pluginInnkeeper:
      generated: false
  pluginValues:
    tractionInnkeeper:
      printKey: true
      printToken: true
      reservationExpiryMinutes: 2880
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
  tails:
    enabled: true
postgresql:
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
tenant_proxy:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-proxy:0.2.11"
    version: '0.2.11'
    buildtime: "2022-01-28T18:19:10.574Z"
    pullPolicy: Always