global:
  fullnameOverride: "traction-dts"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
  nsp:
    enabled: true
acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:sha-f678ca9"
    version: 'sha-f678ca9'
    buildtime: '2023-02-16T21:45:48.653Z'
    pullPolicy: Always
  secret:
    adminurl:
      generated: true
    pluginInnkeeper:
      generated: true

  plugins:
    basicmessageStorage: true
    connectionUpdate: true
    multitenantProvider: true
    tractionInnkeeper: true

  pluginValues:
    tractionInnkeeper:
      printKey: true
      printToken: true

  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
  tails:
    enabled: true
  staticArgs:
    walletName: mywallet

postgresql:
  fullnameOverride: 'traction-dts'
  auth:
    existingSecret: traction-dts-db
    secretKeys:
      adminPasswordKey: postgresql-password
      userPasswordKey: postgresql-password
    # -- PostgreSQL Database to create.
    database: traction
    username: postgres
  primary:
    podLabels:
      backup: 'true'
      env: dev
    resources:
      limits:
        cpu: 200m
        memory: 820Mi
      requests:
        cpu: 120m
        memory: 400Mi

tenant_proxy:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-proxy:sha-f678ca9"
    version: 'sha-f678ca9'
    buildtime: "2023-02-16T21:45:38.860Z"
    pullPolicy: Always
