name: Deploy Tenant UI
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Target (github) environment for deployment: development, test, production'
        required: true
        default: 'development'
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: false
        default: ''
      traction_api_endpoint:
        description: 'Traction API Endpoint'
        required: true
        default: 'https://traction-api-dev.apps.silver.devops.gov.bc.ca'
      instance_name:
        description: 'Instance name'
        required: true
        default: 'tenant-ui'

jobs:

  uninstall:
    environment: ${{ github.event.inputs.deploy_env }}
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'bcgov'
    steps:  
      - uses: actions/checkout@v2  
      - name: Check out manifest repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}
          path: charts-repo

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      
      - name: Uninstall via Helm 
        run: |
          helm uninstall "${{ github.event.inputs.instance_name }}"
      
      - name: Remove Openshift Objects 
        run: |
          oc delete secret,pvc --selector "app.kubernetes.io/instance"="${{ github.event.inputs.instance_name }}"

  build_image:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'bcgov'
    steps:      
      - uses: actions/checkout@v2    
        with:
          ref: ${{ github.event.inputs.ref }}    
      
      - name: Build service
        uses: ./.github/actions/build_image
        id: builder
        with:
          ref: ${{ github.event.inputs.ref }}
          context: './services/tenant-ui'
          image_name: ${{ github.repository_owner}}/traction-tenant-ui
          python_image: false
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}          
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  deploy:
    environment: ${{ github.event.inputs.deploy_env }}
    runs-on: ubuntu-20.04
    needs: 
      - build_image
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) && (github.repository_owner == 'bcgov') }}
    
    steps:  
      - uses: actions/checkout@v2  

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Run Helm
        run: |
          yq eval '.global.fullnameOverride = "${{ github.event.inputs.instance_name }}"' -i ./charts/tenant-ui/values.yaml
          yq eval '.tenant_ui.traction_api.endpoint = "${{ github.event.inputs.traction_api_endpoint }}"' -i ./charts/tenant-ui/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.tenant_ui.image.tag = "${{ needs.build_image.outputs.image_tag }}"' -i ./charts/tenant-ui/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.tenant_ui.image.version = "${{ needs.build_image.outputs.image_version }}"' -i ./charts/tenant-ui/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.tenant_ui.image.buildtime = "${{ needs.build_image.outputs.buildtime }}"' -i ./charts/tenant-ui/values-${{ github.event.inputs.deploy_env }}.yaml
          helm upgrade -f ./charts/tenant-ui/values.yaml -f ./charts/tenant-ui/values-${{ github.event.inputs.deploy_env }}.yaml "${{ github.event.inputs.instance_name }}" ./charts/tenant-ui --install --wait
